### ISSUE TITLE
[BUG] Crash with Lootr

### ISSUE THREAD

**Issue by LunarFactory** [ferriarnus/Unidentified-Enchantments#1]
[crash-2022-02-24_11.15.07-server.txt](https://github.com/ferriarnus/Unidentified-Enchantments/files/8129130/crash-2022-02-24_11.15.07-server.txt)
I dunno what actually happened...

**Comment by ferriarnus** [comment]
Thank you for telling me. This might even be an oversight of me related it running on a server, so I will push a fix as soon as possible.

**Comment by ferriarnus** [comment]
@PixVoxel should be fixed in 1.0.2, have a look

**Comment by Spazmunki13** [comment]
I seem to be experiencing an issue with Lootr as well, although the crash report seems different.

[crash-2022-03-13_03.00.37-server.txt](https://github.com/ferriarnus/Unidentified-Enchantments/files/8239099/crash-2022-03-13_03.00.37-server.txt)

**Comment by ferriarnus** [comment]
I think I know what causes it, I'll see if I can fix it.

**Comment by ferriarnus** [comment]
I think this is solved now.
