### ISSUE TITLE
[BUG?] Does not work with Lootr chest

### ISSUE THREAD

**Issue by LunarFactory** [ferriarnus/Unidentified-Enchantments#11]
![image](https://user-images.githubusercontent.com/69113888/166090182-acc3e21d-8404-4e94-9b2a-7bd5eaf69fb1.png)
no hidden on lootr chest.

**Comment by ferriarnus** [comment]
I'll fix it. While lootr extends vanilla chests, he made it so they have no itemhandler capabilty, making my filter fail (again...). Guess I'll just leave a general "chest" name filter in. And while I'm at it I'll do the same for the "barrel" and "shulker" and so on...

**Comment by ferriarnus** [comment]
I re-added the simple filter again, should solve all issues
