### ISSUE TITLE
Crash with Quark .355 and .356

### ISSUE THREAD

**Issue by Freshah** [ferriarnus/Unidentified-Enchantments#15]
https://pastebin.com/CxBH78Vi

Newest UE crashes with Quark again

**Comment by ferriarnus** [comment]
Is this the latest version? I thouht I removed the classes that cause the crash

**Comment by ferriarnus** [comment]
Can you try the new version @Freshah? Are you sure it's this mod, cause I did not get any issue in my testes.

**Comment by Freshah** [comment]
admittedly I can't even reproduce it now.  must be another mod.    New texture looks great!
