### ISSUE TITLE
Game crashes when trying to use quivers from Parry This!

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [ferriarnus/Unidentified-Enchantments#16]
Minecraft version: 1.18.2
Parry this! version: 2.5
Forge Version: 40.1.54
Unidentified Enchantments Version: 1.0.9
Crash Report: https://gist.github.com/NJL5390/0aacf80a53aff0a354c3525ed7795968

Hi,

I have just noticed when testing this mod with a mod called Parry this! (https://www.curseforge.com/minecraft/mc-mods/parrying) that the game crashes whenever I try to use some items from their mod such as the quiver. This crash seems to be in relation to unidentified enchantments as with just one of these mods installed then the game works fine.

I'm not sure if compatibility between these mods would need to be added due to how this mod works but either way it would be great to see this issue addressed between these two mods.

Here is the issue report on the parrying github: https://github.com/theishiopian/Parrying/issues/30

Thanks for the great mod! I have never seen a mod like this before and I love the unique mechanics that it adds and I love how it adds some mystery to enchanted loot!

**Comment by Jonathing** [comment]
This is a compatibility issue with Parry This! and not Unidentified Enchantments.

**Comment by The-Bernician-Lamb** [comment]
Fixed as of Parry This! version 2.5.1
