### ISSUE TITLE
[BUG] Curse of Insomnia bug?

### ISSUE THREAD

**Issue by LunarFactory** [ferriarnus/Unidentified-Enchantments#2]
![image](https://user-images.githubusercontent.com/69113888/155646591-b8c1d928-1cc6-4b92-b27e-80df125180d9.png)
Curse of Insomnia appears in pickaxe. is it bug of this mod?

**Comment by ferriarnus** [comment]
Yeah it seems I missed a check to see if it can be enchanted. Should also be fixed in the next update
