### ISSUE TITLE
[BUG] Enchantment not hidden

### ISSUE THREAD

**Issue by LunarFactory** [ferriarnus/Unidentified-Enchantments#4]
![image](https://user-images.githubusercontent.com/69113888/155651234-a12c190f-fb6f-442a-bd5b-eab93b9335b1.png)
sorry for korean, but it doesn't hide in server.

**Comment by ferriarnus** [comment]
Seems I did not to a good job fixing the previous issue, But I'm doing some more tests, so it should be working in the next version

**Comment by ferriarnus** [comment]
This should be fixed now @PixVoxel
