### ISSUE TITLE
Does not work well with JEI

### ISSUE THREAD

**Issue by LunarFactory** [ferriarnus/Unidentified-Enchantments#6]
JEI show enchantment information and anvil recipes of origin enchantments.

**Comment by ferriarnus** [comment]
Thank you for telling me, didn't realise that. I will look into it, cause that is a reall issue.

**Comment by ferriarnus** [comment]
I have discussed it with mezz and might have found a way to do it. It does however require me to update to 1.18.2, so it will be done in the next version

**Comment by ferriarnus** [comment]
Should be fixed now in 1.0.4 @PixVoxel
