### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by rabrunos** [ferriarnus/Unidentified-Enchantments#7]
Do you accept suggestions for the mod?

I have a big and good suggestion.

In fact, a few days ago my friend and I were talking about what this mod does!
We were going to develop a mod that does exactly what your mod does!

But you were faster and developed first hahahaha

So, I decided to share one of our ideas we had for the project!

If you want to hear it, just tell me, and I'll show you!

**Comment by ferriarnus** [comment]
Yeah I'm open for suggestions! Feel free to share it!

**Comment by rabrunos** [comment]
Thank you!
I'll be posting it here soon!
