### ISSUE TITLE
[BUG] Crash in 1.18.2

### ISSUE THREAD

**Issue by onyxromero** [ferriarnus/Unidentified-Enchantments#9]
https://gist.github.com/CalamitousEnd/4120cdfaeb939669a736d33002588848

`Exception message: java.lang.NoSuchFieldError: LOOT_MODIFIER_SERIALIZERS`

**Comment by Freshah** [comment]
Same errors on recent Forge versions

**Comment by ferriarnus** [comment]
Seems like the registries changed in 1.18.2. I'll look into it when I have some time.

**Comment by Freshah** [comment]
Thanks for letting us know!

**Comment by ferriarnus** [comment]
This should now be fixed
